### PR TITLE
Allow customizing the label

### PR DESCRIPTION
**Pull request by twe4ked**
In our case we want to label the time as memcache.

### CODE REVIEW

**Comment by dewski** [comment]
I like using memcache as the label, I'd opt for just updating `dalli` to `memcache`.

**Comment by twe4ked** [comment]
I'm happy to push a PR to do that but should we keep it customisable so people can do what they want?

**Comment by dewski** [comment]
This is the only feedback I've received regarding the name, I'd prefer to keep it static if possible.

**Comment by twe4ked** [comment]
I've created a new PR (#6) to make the change.

**Pull request closed without merging**
